#!/bin/sh
# backend:tests / files. Sourced by GitLab; run from the project checkout.

test -f src/api/core/authorization.py
test -f src/api/db/models/demande_affectation.py
test -f src/api/db/models/presentation.py
test -f src/api/db/models/visite.py
test -f src/api/db/models/vente.py
test -f src/api/db/models/paiement.py
test -f src/api/db/models/bareme_commission.py
test -f src/api/db/models/parametres_honoraires.py
test -f src/api/db/models/parametres_remuneration.py
test -f src/api/db/models/palier_performance.py
test -f src/api/repositories/demande.py
test -f src/api/repositories/demande_affectation.py
test -f src/api/repositories/presentation.py
test -f src/api/repositories/visite.py
test -f src/api/repositories/vente.py
test -f src/api/repositories/paiement.py
test -f src/api/repositories/bareme_commission.py
test -f src/api/repositories/parametres_honoraires.py
test -f src/api/repositories/parametres_remuneration.py
test -f src/api/repositories/palier_performance.py
test -f src/api/services/demande.py
test -f src/api/services/demande_affectation.py
test -f src/api/services/presentation.py
test -f src/api/services/visite.py
test -f src/api/services/vente.py
test -f src/api/services/remuneration_calculator.py
test -f src/api/services/remuneration.py
test -f src/api/services/paiement.py
test -f src/api/schemas/demande_affectation.py
test -f src/api/schemas/vente.py
test -f src/api/schemas/paiement.py
test -f src/api/schemas/paiement_transition.py
test -f src/api/api/v1/endpoints/mandats.py
test -f src/api/api/v1/endpoints/demandes.py
test -f src/api/api/v1/endpoints/presentations.py
test -f src/api/api/v1/endpoints/visites.py
test -f src/api/api/v1/endpoints/ventes.py
test -f src/api/api/v1/endpoints/remunerations.py
test -f src/api/api/v1/endpoints/paiements.py
test -f tests/backend/test_demande_affectation_api.py
test -f tests/backend/test_demande_affectation_service.py
test -f tests/backend/test_demande_ownership_api.py
test -f tests/backend/test_presentation_ownership_api.py
test -f tests/backend/test_visite_ownership_api.py
test -f tests/backend/test_visite_audit_api.py
test -f tests/backend/test_vente_service.py
test -f tests/backend/test_vente_api.py
test -f tests/backend/test_remuneration_calculator.py
test -f tests/backend/test_remuneration_service.py
test -f tests/backend/test_remuneration_api.py
test -f tests/backend/test_paiement_service.py
test -f tests/backend/test_paiement_api.py
