stages:
  - validate
  - database
  - deploy

include:
  - local: .gitlab/ci/database.yml
  - local: .gitlab/ci/airflow.yml
  - local: .gitlab/ci/data-pipeline-image.yml
  - local: .gitlab/ci/warehouse.yml
  - local: .gitlab/ci/openmetadata.yml
  - local: .gitlab/ci/governance.yml