stages:
  - validate
  - database
  - build
  - deploy

include:
  - local: .gitlab/ci/database.yml
  - local: .gitlab/ci/airflow.yml
  - local: .gitlab/ci/data-pipeline-image.yml
  - local: .gitlab/ci/warehouse.yml
  - local: .gitlab/ci/governance.yml
  - local: .gitlab/ci/openmetadata.yml
  - local: .gitlab/ci/observability.yml
  - local: .gitlab/ci/backend-tests.yml
  - local: .gitlab/ci/backend.yml
  - local: .gitlab/ci/ai.yml