FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip \
    && pip install -r /app/requirements.txt

COPY database/seeds/generer_annonces.py /app/database/seeds/generer_annonces.py
COPY database/seeds/load_raw_generated_data.py /app/database/seeds/load_raw_generated_data.py
COPY database/seeds/upload_generated_to_s3.py /app/database/seeds/upload_generated_to_s3.py
COPY database/seeds/download_generated_from_s3.py /app/database/seeds/download_generated_from_s3.py
COPY database/tests/004_raw_data_quality.sql /app/database/tests/004_raw_data_quality.sql
COPY database/seeds/transform_raw_to_staging.py /app/database/seeds/transform_raw_to_staging.py
COPY database/tests/005_staging_data_quality.sql /app/database/tests/005_staging_data_quality.sql
COPY database/seeds/load_staging_to_oltp.py /app/database/seeds/load_staging_to_oltp.py

RUN mkdir -p /app/database/fixtures/annonces/json

ENTRYPOINT ["python"]