-- =============================================================================
-- 006_auth_identity.sql
-- Real Estate Intelligence Platform
--
-- Purpose:
--   Introduce a dedicated authentication identity model for the Backend/API.
--
-- Security architecture:
--
--   utilisateur
--        |
--        +--> CLIENT    -> real_estate.client
--        |
--        +--> CHASSEUR  -> real_estate.chasseur
--        |
--        +--> ADMIN
--        |
--        +--> SERVICE
--
-- Design principles:
--
--   - authentication identity is separated from business entities;
--   - client/chasseur tables do NOT store passwords;
--   - plaintext passwords are NEVER stored;
--   - only a cryptographic password hash may be persisted;
--   - roles are explicitly constrained;
--   - identities can be disabled without deleting business records;
--   - one business entity can have at most one authentication identity;
--   - no default account or credential is created by this migration.
--
-- Future application responsibilities:
--
--   - password hashing and verification;
--   - JWT/token issuance;
--   - authentication endpoint;
--   - role-based authorization;
--   - authenticated actor propagation to audit logs.
-- =============================================================================

\set ON_ERROR_STOP on

BEGIN;


-- =============================================================================
-- 1. PRECONDITIONS
-- =============================================================================

DO $$
BEGIN
    IF to_regclass('real_estate.client') IS NULL THEN
        RAISE EXCEPTION
            'Migration 006 aborted: real_estate.client does not exist';
    END IF;

    IF to_regclass('real_estate.chasseur') IS NULL THEN
        RAISE EXCEPTION
            'Migration 006 aborted: real_estate.chasseur does not exist';
    END IF;

    IF to_regclass('migration_control.schema_version') IS NULL THEN
        RAISE EXCEPTION
            'Migration 006 aborted: migration_control.schema_version does not exist';
    END IF;
END
$$;


-- =============================================================================
-- 2. PREVENT ACCIDENTAL SECOND EXECUTION
-- =============================================================================

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM migration_control.schema_version
        WHERE version = '006'
    ) THEN
        RAISE EXCEPTION
            'Migration 006 has already been applied';
    END IF;
END
$$;


-- =============================================================================
-- 3. AUTHENTICATION IDENTITY
--
-- Important:
--
-- password_hash contains ONLY a cryptographic password hash.
--
-- It must never contain:
--
--   - plaintext passwords;
--   - reversible encrypted passwords;
--   - temporary clear-text credentials.
--
-- Actual hashing is the responsibility of the Backend authentication service.
-- =============================================================================

CREATE TABLE real_estate.utilisateur (
    id_utilisateur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(255) NOT NULL,

    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(20) NOT NULL,

    actif BOOLEAN NOT NULL DEFAULT TRUE,

    id_client BIGINT,

    id_chasseur BIGINT,

    derniere_connexion TIMESTAMPTZ,

    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    date_modification TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_utilisateur_role
        CHECK (
            role IN (
                'ADMIN',
                'CLIENT',
                'CHASSEUR',
                'SERVICE'
            )
        ),

    CONSTRAINT fk_utilisateur_client
        FOREIGN KEY (id_client)
        REFERENCES real_estate.client(id_client)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_utilisateur_chasseur
        FOREIGN KEY (id_chasseur)
        REFERENCES real_estate.chasseur(id_chasseur)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);


-- =============================================================================
-- 4. ROLE / BUSINESS-ENTITY CONSISTENCY
--
-- CLIENT:
--   must reference exactly one client.
--
-- CHASSEUR:
--   must reference exactly one chasseur.
--
-- ADMIN / SERVICE:
--   must not impersonate a client or chasseur business entity.
-- =============================================================================

ALTER TABLE real_estate.utilisateur
    ADD CONSTRAINT ck_utilisateur_business_identity
    CHECK (
        (
            role = 'CLIENT'
            AND id_client IS NOT NULL
            AND id_chasseur IS NULL
        )
        OR
        (
            role = 'CHASSEUR'
            AND id_chasseur IS NOT NULL
            AND id_client IS NULL
        )
        OR
        (
            role IN ('ADMIN', 'SERVICE')
            AND id_client IS NULL
            AND id_chasseur IS NULL
        )
    );


-- =============================================================================
-- 5. UNIQUENESS
--
-- Email authentication is case-insensitive.
--
-- PostgreSQL UNIQUE(email) alone would allow:
--
--   User@example.com
--   user@example.com
--
-- simultaneously.
--
-- The functional unique index prevents this ambiguity.
-- =============================================================================

CREATE UNIQUE INDEX uq_utilisateur_email_lower
    ON real_estate.utilisateur (
        LOWER(email)
    );


-- A client may have at most one authentication identity.

CREATE UNIQUE INDEX uq_utilisateur_client
    ON real_estate.utilisateur(id_client)
    WHERE id_client IS NOT NULL;


-- A hunter may have at most one authentication identity.

CREATE UNIQUE INDEX uq_utilisateur_chasseur
    ON real_estate.utilisateur(id_chasseur)
    WHERE id_chasseur IS NOT NULL;


-- =============================================================================
-- 6. OPERATIONAL INDEXES
-- =============================================================================

CREATE INDEX idx_utilisateur_role
    ON real_estate.utilisateur(role);


CREATE INDEX idx_utilisateur_actif
    ON real_estate.utilisateur(actif);


-- =============================================================================
-- 7. PASSWORD-HASH SAFETY CONSTRAINT
--
-- This is NOT password-hash algorithm validation.
--
-- It only prevents obviously invalid / empty values from being persisted.
--
-- Algorithm validation remains an application responsibility.
-- =============================================================================

ALTER TABLE real_estate.utilisateur
    ADD CONSTRAINT ck_utilisateur_password_hash_non_empty
    CHECK (
        LENGTH(TRIM(password_hash)) >= 20
    );


-- =============================================================================
-- 8. EMAIL SAFETY CONSTRAINT
--
-- Full RFC email validation belongs to the application layer.
--
-- The database constraint only rejects clearly malformed values.
-- =============================================================================

ALTER TABLE real_estate.utilisateur
    ADD CONSTRAINT ck_utilisateur_email_basic
    CHECK (
        email = TRIM(email)
        AND POSITION('@' IN email) > 1
        AND LENGTH(email) <= 255
    );


-- =============================================================================
-- 9. NO AUTOMATIC ACCOUNT CREATION
--
-- This migration deliberately inserts ZERO authentication identities.
--
-- Reasons:
--
--   - no default password in Git;
--   - no shared administrator credential;
--   - no plaintext bootstrap credential;
--   - no automatic conversion of legacy users into authenticated accounts.
--
-- Account provisioning will be handled by controlled application logic.
-- =============================================================================


-- =============================================================================
-- 10. VALIDATION
-- =============================================================================

DO $$
DECLARE
    utilisateur_table_exists BOOLEAN;
    utilisateur_count INTEGER;
    email_index_count INTEGER;
BEGIN
    SELECT to_regclass('real_estate.utilisateur') IS NOT NULL
    INTO utilisateur_table_exists;

    IF NOT utilisateur_table_exists THEN
        RAISE EXCEPTION
            'Migration 006 validation failed: real_estate.utilisateur was not created';
    END IF;


    SELECT COUNT(*)
    INTO utilisateur_count
    FROM real_estate.utilisateur;

    IF utilisateur_count <> 0 THEN
        RAISE EXCEPTION
            'Migration 006 validation failed: expected 0 bootstrap users, found %',
            utilisateur_count;
    END IF;


    SELECT COUNT(*)
    INTO email_index_count
    FROM pg_indexes
    WHERE schemaname = 'real_estate'
      AND tablename = 'utilisateur'
      AND indexname = 'uq_utilisateur_email_lower';

    IF email_index_count <> 1 THEN
        RAISE EXCEPTION
            'Migration 006 validation failed: email uniqueness index missing';
    END IF;


    RAISE NOTICE
        'PASS: real_estate.utilisateur authentication identity created';

    RAISE NOTICE
        'PASS: authentication identity is separated from client/chasseur business entities';

    RAISE NOTICE
        'PASS: no default authentication account was created';

    RAISE NOTICE
        'PASS: case-insensitive email uniqueness is enforced';

    RAISE NOTICE
        'PASS: client/chasseur identity relationships are constrained';
END
$$;


-- =============================================================================
-- 11. REGISTER MIGRATION
-- =============================================================================

INSERT INTO migration_control.schema_version (
    version,
    description
)
VALUES (
    '006',
    'Add dedicated authentication identity and role model'
);


COMMIT;


-- =============================================================================
-- POST-MIGRATION REPORT
-- =============================================================================

SELECT
    version,
    description,
    applied_at
FROM migration_control.schema_version
WHERE version = '006';


SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'real_estate'
  AND table_name = 'utilisateur';


SELECT
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'real_estate'
  AND table_name = 'utilisateur'
ORDER BY ordinal_position;


SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'real_estate'
  AND tablename = 'utilisateur'
ORDER BY indexname;