BEGIN;

-- =============================================================================
-- Migration 009
-- Add Mandat contractual period lifecycle to analytical warehouse
--
-- Source:
--   real_estate.mandat_periode
--
-- Grain:
--   1 row per contractual Mandat period
--
-- Purpose:
--   Preserve Mandat renewal history in the analytical warehouse without
--   changing the existing grain of warehouse.fact_mandat.
-- =============================================================================

CREATE TABLE warehouse.fact_mandat_periode (
    mandat_periode_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    id_mandat_periode_source BIGINT NOT NULL,
    mandat_fact_key BIGINT NOT NULL,

    numero_periode INTEGER NOT NULL,
    type_periode VARCHAR(32) NOT NULL,

    date_debut_key INTEGER NOT NULL,
    date_fin_key INTEGER NOT NULL,
    date_renouvellement_key INTEGER NULL,

    est_historique_legacy BOOLEAN NOT NULL DEFAULT FALSE,

    duree_jours INTEGER NOT NULL,
    periode_count SMALLINT NOT NULL DEFAULT 1,

    created_at_source TIMESTAMPTZ NOT NULL,
    dw_loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_fact_mandat_periode
        PRIMARY KEY (mandat_periode_fact_key),

    CONSTRAINT uq_fact_mandat_periode_source
        UNIQUE (id_mandat_periode_source),

    CONSTRAINT uq_fact_mandat_periode_numero
        UNIQUE (mandat_fact_key, numero_periode),

    CONSTRAINT fk_fact_mandat_periode_mandat
        FOREIGN KEY (mandat_fact_key)
        REFERENCES warehouse.fact_mandat(mandat_fact_key)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fact_mandat_periode_date_debut
        FOREIGN KEY (date_debut_key)
        REFERENCES warehouse.dim_date(date_key)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fact_mandat_periode_date_fin
        FOREIGN KEY (date_fin_key)
        REFERENCES warehouse.dim_date(date_key)
        ON DELETE RESTRICT,

    CONSTRAINT fk_fact_mandat_periode_date_renouvellement
        FOREIGN KEY (date_renouvellement_key)
        REFERENCES warehouse.dim_date(date_key)
        ON DELETE RESTRICT,

    CONSTRAINT ck_fact_mandat_periode_numero
        CHECK (numero_periode >= 1),

    CONSTRAINT ck_fact_mandat_periode_type
        CHECK (type_periode IN ('INITIAL', 'RENOUVELLEMENT')),

    CONSTRAINT ck_fact_mandat_periode_duree
        CHECK (duree_jours >= 0),

    CONSTRAINT ck_fact_mandat_periode_count
        CHECK (periode_count = 1),

    CONSTRAINT ck_fact_mandat_periode_renouvellement
        CHECK (
            (
                type_periode = 'INITIAL'
                AND date_renouvellement_key IS NULL
            )
            OR
            (
                type_periode = 'RENOUVELLEMENT'
                AND date_renouvellement_key IS NOT NULL
            )
        )
);

-- =============================================================================
-- Indexes
-- =============================================================================

CREATE INDEX idx_fact_mandat_periode_mandat
    ON warehouse.fact_mandat_periode(mandat_fact_key);

CREATE INDEX idx_fact_mandat_periode_type
    ON warehouse.fact_mandat_periode(type_periode);

CREATE INDEX idx_fact_mandat_periode_date_debut
    ON warehouse.fact_mandat_periode(date_debut_key);

CREATE INDEX idx_fact_mandat_periode_date_fin
    ON warehouse.fact_mandat_periode(date_fin_key);

CREATE INDEX idx_fact_mandat_periode_date_renouvellement
    ON warehouse.fact_mandat_periode(date_renouvellement_key)
    WHERE date_renouvellement_key IS NOT NULL;

-- =============================================================================
-- Initial load / backfill
--
-- warehouse.fact_mandat already contains exactly one row per Mandat.
-- The new fact references that existing Mandat fact row.
-- =============================================================================

INSERT INTO warehouse.fact_mandat_periode (
    id_mandat_periode_source,
    mandat_fact_key,
    numero_periode,
    type_periode,
    date_debut_key,
    date_fin_key,
    date_renouvellement_key,
    est_historique_legacy,
    duree_jours,
    periode_count,
    created_at_source,
    dw_loaded_at
)
SELECT
    mp.id_mandat_periode,
    fm.mandat_fact_key,
    mp.numero_periode,
    mp.type_periode,
    TO_CHAR(mp.date_debut, 'YYYYMMDD')::INTEGER,
    TO_CHAR(mp.date_fin, 'YYYYMMDD')::INTEGER,
    CASE
        WHEN mp.date_renouvellement IS NULL
            THEN NULL
        ELSE TO_CHAR(mp.date_renouvellement, 'YYYYMMDD')::INTEGER
    END,
    mp.est_historique_legacy,
    (mp.date_fin - mp.date_debut),
    1,
    mp.created_at,
    CURRENT_TIMESTAMP
FROM real_estate.mandat_periode mp
JOIN warehouse.fact_mandat fm
  ON fm.id_mandat_source = mp.id_mandat
ON CONFLICT (id_mandat_periode_source)
DO NOTHING;

-- =============================================================================
-- Migration registry
-- =============================================================================

INSERT INTO migration_control.schema_version (
    version,
    description
)
VALUES (
    '009',
    'Add Mandat period lifecycle fact to analytical warehouse'
);

COMMIT;