BEGIN;

-- =============================================================================
-- Migration 010
-- Transaction and remuneration foundation
--
-- Business flow:
--
--   Mandat
--      |
--      v
--   Vente / acte authentique
--      |
--      v
--   Calcul de remuneration
--      |
--      v
--   Paiement
--
-- Goals:
--   - represent the completed sale independently from the payment lifecycle;
--   - preserve the Mandat / Bien / Presentation / hunter context of the sale;
--   - version company-fee parameters;
--   - version remuneration-performance parameters;
--   - support default and hunter-specific commission grids;
--   - prevent migrated legacy rates from being silently used as approved
--     operational remuneration grids;
--   - freeze all material inputs and outputs of a remuneration calculation;
--   - preserve all existing data and columns.
--
-- Important:
--   The numeric values proposed in the teaching material
--   (3000 EUR + 2.5%, commission bands, weights, modulation, etc.)
--   are configuration decisions, not immutable business rules.
--
--   This migration therefore creates the structures but DOES NOT seed those
--   example parameter values as production configuration.
-- =============================================================================


-- =============================================================================
-- 1. Completed transaction / sale
--
-- A sale is created when an authentic deed is signed.
--
-- id_presentation and id_bien are nullable deliberately:
--
--   - an exclusive Mandat may still remunerate the hunter when the client
--     found the property independently;
--   - a transaction originating outside the internal recommendation flow
--     may therefore have no internal Presentation.
--
-- id_mandat_periode identifies the contractual period giving entitlement
-- when such a valid period exists at the deed date.
-- =============================================================================

CREATE TABLE real_estate.vente (
    id_vente BIGINT GENERATED BY DEFAULT AS IDENTITY,

    id_mandat BIGINT NOT NULL,
    id_mandat_periode BIGINT NULL,

    id_presentation BIGINT NULL,
    id_bien BIGINT NULL,

    id_chasseur_beneficiaire BIGINT NULL,

    origine_vente VARCHAR(32) NOT NULL,

    date_acte_authentique DATE NOT NULL,
    montant_achat NUMERIC(14, 2) NOT NULL,

    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_vente
        PRIMARY KEY (id_vente),

    CONSTRAINT fk_vente_mandat
        FOREIGN KEY (id_mandat)
        REFERENCES real_estate.mandat(id_mandat)
        ON DELETE RESTRICT,

    CONSTRAINT fk_vente_mandat_periode
        FOREIGN KEY (id_mandat_periode)
        REFERENCES real_estate.mandat_periode(id_mandat_periode)
        ON DELETE RESTRICT,

    CONSTRAINT fk_vente_presentation
        FOREIGN KEY (id_presentation)
        REFERENCES real_estate.presentation(id_presentation)
        ON DELETE RESTRICT,

    CONSTRAINT fk_vente_bien
        FOREIGN KEY (id_bien)
        REFERENCES real_estate.bien(id_bien)
        ON DELETE RESTRICT,

    CONSTRAINT fk_vente_chasseur_beneficiaire
        FOREIGN KEY (id_chasseur_beneficiaire)
        REFERENCES real_estate.chasseur(id_chasseur)
        ON DELETE RESTRICT,

    CONSTRAINT ck_vente_origine
        CHECK (
            origine_vente IN (
                'CHASSEUR',
                'CLIENT_SEUL',
                'AUTRE_AGENCE'
            )
        ),

    CONSTRAINT ck_vente_montant_achat
        CHECK (montant_achat > 0)
);


-- A Presentation can result in at most one completed sale.
CREATE UNIQUE INDEX uq_vente_presentation
    ON real_estate.vente(id_presentation)
    WHERE id_presentation IS NOT NULL;


CREATE INDEX idx_vente_mandat
    ON real_estate.vente(id_mandat);

CREATE INDEX idx_vente_mandat_periode
    ON real_estate.vente(id_mandat_periode)
    WHERE id_mandat_periode IS NOT NULL;

CREATE INDEX idx_vente_bien
    ON real_estate.vente(id_bien)
    WHERE id_bien IS NOT NULL;

CREATE INDEX idx_vente_chasseur_beneficiaire
    ON real_estate.vente(id_chasseur_beneficiaire)
    WHERE id_chasseur_beneficiaire IS NOT NULL;

CREATE INDEX idx_vente_date_acte
    ON real_estate.vente(date_acte_authentique);

CREATE INDEX idx_vente_origine
    ON real_estate.vente(origine_vente);


-- =============================================================================
-- 2. Versioned company-fee parameters
--
-- Business formula:
--
--     H = F + t * P
--
-- H = company fees
-- F = fixed component
-- t = percentage component
-- P = purchase price
--
-- Parameters are selected according to the authentic-deed date.
-- =============================================================================

CREATE TABLE real_estate.parametres_honoraires (
    id_parametres_honoraires BIGINT GENERATED BY DEFAULT AS IDENTITY,

    date_debut_validite DATE NOT NULL,
    date_fin_validite DATE NULL,

    montant_fixe NUMERIC(14, 2) NOT NULL,
    taux_pourcentage NUMERIC(9, 6) NOT NULL,

    actif BOOLEAN NOT NULL DEFAULT TRUE,

    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_parametres_honoraires
        PRIMARY KEY (id_parametres_honoraires),

    CONSTRAINT ck_parametres_honoraires_dates
        CHECK (
            date_fin_validite IS NULL
            OR date_fin_validite >= date_debut_validite
        ),

    CONSTRAINT ck_parametres_honoraires_montant_fixe
        CHECK (montant_fixe >= 0),

    CONSTRAINT ck_parametres_honoraires_taux
        CHECK (
            taux_pourcentage >= 0
            AND taux_pourcentage <= 1
        )
);


CREATE INDEX idx_parametres_honoraires_validite
    ON real_estate.parametres_honoraires(
        date_debut_validite,
        date_fin_validite
    );

CREATE INDEX idx_parametres_honoraires_actif
    ON real_estate.parametres_honoraires(actif)
    WHERE actif = TRUE;


-- -----------------------------------------------------------------------------
-- Prevent overlapping active company-fee configurations.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION real_estate.prevent_parametres_honoraires_overlap()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.actif THEN

        IF EXISTS (
            SELECT 1
            FROM real_estate.parametres_honoraires p
            WHERE p.id_parametres_honoraires <> NEW.id_parametres_honoraires
              AND p.actif = TRUE
              AND daterange(
                    p.date_debut_validite,
                    COALESCE(
                        p.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )
                  &&
                  daterange(
                    NEW.date_debut_validite,
                    COALESCE(
                        NEW.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )
        ) THEN
            RAISE EXCEPTION
                'Overlapping active company-fee parameter period';
        END IF;

    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_parametres_honoraires_no_overlap
BEFORE INSERT OR UPDATE
ON real_estate.parametres_honoraires
FOR EACH ROW
EXECUTE FUNCTION real_estate.prevent_parametres_honoraires_overlap();


-- =============================================================================
-- 3. Versioned remuneration/performance parameters
--
-- These values are parameters, not hard-coded business rules.
--
-- The five mandatory business criteria remain:
--
--   - delay Mandat -> authentic deed
--   - exclusivity
--   - successful sales
--   - signed Mandats
--   - visits before purchase
--
-- This table contains the configurable weights and modulation rules.
-- =============================================================================

CREATE TABLE real_estate.parametres_remuneration (
    id_parametres_remuneration BIGINT GENERATED BY DEFAULT AS IDENTITY,

    date_debut_validite DATE NOT NULL,
    date_fin_validite DATE NULL,

    fenetre_mois INTEGER NOT NULL,

    poids_delai NUMERIC(7, 6) NOT NULL,
    poids_exclusivite NUMERIC(7, 6) NOT NULL,
    poids_ventes NUMERIC(7, 6) NOT NULL,
    poids_mandats NUMERIC(7, 6) NOT NULL,
    poids_visites NUMERIC(7, 6) NOT NULL,

    note_exclusif NUMERIC(5, 2) NOT NULL,
    note_non_exclusif NUMERIC(5, 2) NOT NULL,

    points_par_vente NUMERIC(5, 2) NOT NULL,
    points_par_mandat NUMERIC(5, 2) NOT NULL,

    taux_anciennete_par_annee NUMERIC(9, 6) NOT NULL,
    plafond_anciennete NUMERIC(9, 6) NOT NULL,

    score_pivot NUMERIC(5, 2) NOT NULL,
    amplitude_performance NUMERIC(9, 6) NOT NULL,

    taux_plancher NUMERIC(9, 6) NOT NULL,
    taux_plafond NUMERIC(9, 6) NOT NULL,

    actif BOOLEAN NOT NULL DEFAULT TRUE,

    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_parametres_remuneration
        PRIMARY KEY (id_parametres_remuneration),

    CONSTRAINT ck_parametres_remuneration_dates
        CHECK (
            date_fin_validite IS NULL
            OR date_fin_validite >= date_debut_validite
        ),

    CONSTRAINT ck_parametres_remuneration_fenetre
        CHECK (fenetre_mois > 0),

    CONSTRAINT ck_parametres_remuneration_poids
        CHECK (
            poids_delai >= 0
            AND poids_exclusivite >= 0
            AND poids_ventes >= 0
            AND poids_mandats >= 0
            AND poids_visites >= 0
            AND (
                poids_delai
                + poids_exclusivite
                + poids_ventes
                + poids_mandats
                + poids_visites
            ) = 1.000000
        ),

    CONSTRAINT ck_parametres_remuneration_notes
        CHECK (
            note_exclusif BETWEEN 0 AND 100
            AND note_non_exclusif BETWEEN 0 AND 100
        ),

    CONSTRAINT ck_parametres_remuneration_points
        CHECK (
            points_par_vente >= 0
            AND points_par_mandat >= 0
        ),

    CONSTRAINT ck_parametres_remuneration_anciennete
        CHECK (
            taux_anciennete_par_annee >= 0
            AND plafond_anciennete >= 0
            AND plafond_anciennete <= 1
        ),

    CONSTRAINT ck_parametres_remuneration_score_pivot
        CHECK (score_pivot BETWEEN 0 AND 100),

    CONSTRAINT ck_parametres_remuneration_amplitude
        CHECK (
            amplitude_performance >= 0
            AND amplitude_performance <= 1
        ),

    CONSTRAINT ck_parametres_remuneration_taux
        CHECK (
            taux_plancher >= 0
            AND taux_plafond <= 1
            AND taux_plancher <= taux_plafond
        )
);


CREATE INDEX idx_parametres_remuneration_validite
    ON real_estate.parametres_remuneration(
        date_debut_validite,
        date_fin_validite
    );

CREATE INDEX idx_parametres_remuneration_actif
    ON real_estate.parametres_remuneration(actif)
    WHERE actif = TRUE;


-- -----------------------------------------------------------------------------
-- Prevent overlapping active remuneration configurations.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION real_estate.prevent_parametres_remuneration_overlap()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.actif THEN

        IF EXISTS (
            SELECT 1
            FROM real_estate.parametres_remuneration p
            WHERE p.id_parametres_remuneration <> NEW.id_parametres_remuneration
              AND p.actif = TRUE
              AND daterange(
                    p.date_debut_validite,
                    COALESCE(
                        p.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )
                  &&
                  daterange(
                    NEW.date_debut_validite,
                    COALESCE(
                        NEW.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )
        ) THEN
            RAISE EXCEPTION
                'Overlapping active remuneration parameter period';
        END IF;

    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_parametres_remuneration_no_overlap
BEFORE INSERT OR UPDATE
ON real_estate.parametres_remuneration
FOR EACH ROW
EXECUTE FUNCTION real_estate.prevent_parametres_remuneration_overlap();


-- =============================================================================
-- 4. Performance scoring bands
--
-- The criteria themselves are mandatory.
-- The actual thresholds and scores remain configurable parameters.
--
-- borne_max NULL means the final open-ended band.
-- ordre controls deterministic evaluation order.
-- =============================================================================

CREATE TABLE real_estate.palier_performance (
    id_palier_performance BIGINT GENERATED BY DEFAULT AS IDENTITY,

    id_parametres_remuneration BIGINT NOT NULL,

    critere VARCHAR(32) NOT NULL,

    ordre INTEGER NOT NULL,
    borne_max INTEGER NULL,

    note NUMERIC(5, 2) NOT NULL,

    CONSTRAINT pk_palier_performance
        PRIMARY KEY (id_palier_performance),

    CONSTRAINT fk_palier_performance_parametres
        FOREIGN KEY (id_parametres_remuneration)
        REFERENCES real_estate.parametres_remuneration(
            id_parametres_remuneration
        )
        ON DELETE RESTRICT,

    CONSTRAINT uq_palier_performance_ordre
        UNIQUE (
            id_parametres_remuneration,
            critere,
            ordre
        ),

    CONSTRAINT ck_palier_performance_critere
        CHECK (
            critere IN (
                'DELAI_SEMAINES',
                'VISITES'
            )
        ),

    CONSTRAINT ck_palier_performance_ordre
        CHECK (ordre >= 1),

    CONSTRAINT ck_palier_performance_borne
        CHECK (
            borne_max IS NULL
            OR borne_max >= 0
        ),

    CONSTRAINT ck_palier_performance_note
        CHECK (note BETWEEN 0 AND 100)
);


CREATE INDEX idx_palier_performance_parametres
    ON real_estate.palier_performance(
        id_parametres_remuneration
    );

CREATE INDEX idx_palier_performance_critere
    ON real_estate.palier_performance(
        id_parametres_remuneration,
        critere,
        ordre
    );


-- =============================================================================
-- 5. Commission grid evolution
--
-- Existing rows originate from the legacy migration.
--
-- They preserve the legacy numeric values but their original business meaning
-- is ambiguous. They MUST NOT silently become operational remuneration grids.
--
-- statut_usage:
--
--   HISTORIQUE = migrated / retained for traceability
--   APPROUVE    = explicitly approved for operational calculation
--
-- id_chasseur NULL represents the default grid.
--
-- Operational price interval convention:
--
--   montant_min is inclusive
--   montant_max is exclusive
--   montant_max NULL means no upper limit
--
-- Example:
--
--   [0, 200000)
--   [200000, 350000)
--   [350000, 500000)
-- =============================================================================

ALTER TABLE real_estate.bareme_commission
    ALTER COLUMN id_chasseur DROP NOT NULL;


ALTER TABLE real_estate.bareme_commission
    ADD COLUMN statut_usage VARCHAR(24)
        NOT NULL
        DEFAULT 'HISTORIQUE';


ALTER TABLE real_estate.bareme_commission
    ADD CONSTRAINT ck_bareme_commission_statut_usage
    CHECK (
        statut_usage IN (
            'HISTORIQUE',
            'APPROUVE'
        )
    );


-- The current legacy rows stay explicitly historical.
UPDATE real_estate.bareme_commission
SET statut_usage = 'HISTORIQUE';


CREATE INDEX idx_bareme_commission_selection
    ON real_estate.bareme_commission(
        id_chasseur,
        date_debut_validite,
        date_fin_validite,
        montant_min,
        montant_max
    )
    WHERE actif = TRUE
      AND statut_usage = 'APPROUVE';


CREATE INDEX idx_bareme_commission_defaut
    ON real_estate.bareme_commission(
        date_debut_validite,
        date_fin_validite,
        montant_min,
        montant_max
    )
    WHERE id_chasseur IS NULL
      AND actif = TRUE
      AND statut_usage = 'APPROUVE';


COMMENT ON COLUMN real_estate.bareme_commission.montant_min IS
    'Operational APPROUVE grids use an inclusive lower bound.';

COMMENT ON COLUMN real_estate.bareme_commission.montant_max IS
    'Operational APPROUVE grids use an exclusive upper bound; NULL means no upper bound.';

COMMENT ON COLUMN real_estate.bareme_commission.statut_usage IS
    'HISTORIQUE preserves migrated legacy values; APPROUVE is eligible for operational remuneration calculation.';


-- -----------------------------------------------------------------------------
-- Prevent overlapping approved commission-grid lines.
--
-- Overlap is checked for:
--
--   same hunter/default scope
--   overlapping validity period
--   overlapping price range
--
-- Hunter-specific and default grids may overlap each other deliberately:
-- a hunter-specific grid overrides the default grid in application logic.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION real_estate.prevent_bareme_commission_overlap()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.actif
       AND NEW.statut_usage = 'APPROUVE'
    THEN

        IF EXISTS (
            SELECT 1
            FROM real_estate.bareme_commission b
            WHERE b.id_bareme <> NEW.id_bareme
              AND b.actif = TRUE
              AND b.statut_usage = 'APPROUVE'

              AND b.id_chasseur IS NOT DISTINCT FROM NEW.id_chasseur

              AND daterange(
                    b.date_debut_validite,
                    COALESCE(
                        b.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )
                  &&
                  daterange(
                    NEW.date_debut_validite,
                    COALESCE(
                        NEW.date_fin_validite + 1,
                        'infinity'::date
                    ),
                    '[)'
                  )

              AND numrange(
                    b.montant_min,
                    b.montant_max,
                    '[)'
                  )
                  &&
                  numrange(
                    NEW.montant_min,
                    NEW.montant_max,
                    '[)'
                  )
        ) THEN
            RAISE EXCEPTION
                'Overlapping approved commission grid for hunter scope %',
                COALESCE(
                    NEW.id_chasseur::TEXT,
                    'DEFAULT'
                );
        END IF;

    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_bareme_commission_no_overlap
BEFORE INSERT OR UPDATE
ON real_estate.bareme_commission
FOR EACH ROW
EXECUTE FUNCTION real_estate.prevent_bareme_commission_overlap();


-- =============================================================================
-- 6. Extend paiement with immutable remuneration calculation evidence
--
-- Existing columns are deliberately preserved:
--
--   date_acte_authentique
--   montant_achat
--   montant_honoraires
--   montant_chasseur
--   id_mandat
--   id_bareme
--
-- They remain compatible with the existing warehouse loader.
--
-- New columns freeze the complete explanation of the remuneration calculation.
-- =============================================================================

ALTER TABLE real_estate.paiement
    ADD COLUMN id_vente BIGINT NULL,

    ADD COLUMN id_chasseur_beneficiaire BIGINT NULL,

    ADD COLUMN id_parametres_honoraires BIGINT NULL,

    ADD COLUMN id_parametres_remuneration BIGINT NULL,

    ADD COLUMN date_calcul TIMESTAMPTZ NULL,

    ADD COLUMN droit_remuneration BOOLEAN NULL,

    ADD COLUMN motif_refus VARCHAR(32) NULL,

    ADD COLUMN semaines_mandat_acte INTEGER NULL,

    ADD COLUMN nb_visites_calcul INTEGER NULL,

    ADD COLUMN annees_anciennete_calcul INTEGER NULL,

    ADD COLUMN nb_ventes_fenetre INTEGER NULL,

    ADD COLUMN nb_mandats_fenetre INTEGER NULL,

    ADD COLUMN note_delai NUMERIC(5, 2) NULL,

    ADD COLUMN note_exclusivite NUMERIC(5, 2) NULL,

    ADD COLUMN note_ventes NUMERIC(5, 2) NULL,

    ADD COLUMN note_mandats NUMERIC(5, 2) NULL,

    ADD COLUMN note_visites NUMERIC(5, 2) NULL,

    ADD COLUMN score_performance NUMERIC(5, 2) NULL,

    ADD COLUMN taux_base NUMERIC(9, 6) NULL,

    ADD COLUMN majoration_anciennete NUMERIC(9, 6) NULL,

    ADD COLUMN modulation_performance NUMERIC(9, 6) NULL,

    ADD COLUMN taux_final NUMERIC(9, 6) NULL;


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT fk_paiement_vente
        FOREIGN KEY (id_vente)
        REFERENCES real_estate.vente(id_vente)
        ON DELETE RESTRICT,

    ADD CONSTRAINT fk_paiement_chasseur_beneficiaire
        FOREIGN KEY (id_chasseur_beneficiaire)
        REFERENCES real_estate.chasseur(id_chasseur)
        ON DELETE RESTRICT,

    ADD CONSTRAINT fk_paiement_parametres_honoraires
        FOREIGN KEY (id_parametres_honoraires)
        REFERENCES real_estate.parametres_honoraires(
            id_parametres_honoraires
        )
        ON DELETE RESTRICT,

    ADD CONSTRAINT fk_paiement_parametres_remuneration
        FOREIGN KEY (id_parametres_remuneration)
        REFERENCES real_estate.parametres_remuneration(
            id_parametres_remuneration
        )
        ON DELETE RESTRICT;


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_motif_refus
    CHECK (
        motif_refus IS NULL
        OR motif_refus IN (
            'MANDAT_EXPIRE',
            'HORS_DISPOSITIF'
        )
    );


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_droit_motif
    CHECK (
        droit_remuneration IS NULL

        OR (
            droit_remuneration = TRUE
            AND motif_refus IS NULL
        )

        OR (
            droit_remuneration = FALSE
            AND motif_refus IS NOT NULL
        )
    );


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_semaines_calcul
    CHECK (
        semaines_mandat_acte IS NULL
        OR semaines_mandat_acte >= 0
    );


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_compteurs_calcul
    CHECK (
        (nb_visites_calcul IS NULL OR nb_visites_calcul >= 0)
        AND (
            annees_anciennete_calcul IS NULL
            OR annees_anciennete_calcul >= 0
        )
        AND (
            nb_ventes_fenetre IS NULL
            OR nb_ventes_fenetre >= 0
        )
        AND (
            nb_mandats_fenetre IS NULL
            OR nb_mandats_fenetre >= 0
        )
    );


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_notes_calcul
    CHECK (
        (note_delai IS NULL OR note_delai BETWEEN 0 AND 100)
        AND (
            note_exclusivite IS NULL
            OR note_exclusivite BETWEEN 0 AND 100
        )
        AND (
            note_ventes IS NULL
            OR note_ventes BETWEEN 0 AND 100
        )
        AND (
            note_mandats IS NULL
            OR note_mandats BETWEEN 0 AND 100
        )
        AND (
            note_visites IS NULL
            OR note_visites BETWEEN 0 AND 100
        )
        AND (
            score_performance IS NULL
            OR score_performance BETWEEN 0 AND 100
        )
    );


ALTER TABLE real_estate.paiement
    ADD CONSTRAINT ck_paiement_taux_calcul
    CHECK (
        (taux_base IS NULL OR taux_base BETWEEN 0 AND 1)
        AND (
            majoration_anciennete IS NULL
            OR majoration_anciennete BETWEEN 0 AND 1
        )
        AND (
            modulation_performance IS NULL
            OR modulation_performance BETWEEN -1 AND 1
        )
        AND (
            taux_final IS NULL
            OR taux_final BETWEEN 0 AND 1
        )
    );


-- One remuneration/payment calculation per completed sale.
CREATE UNIQUE INDEX uq_paiement_vente
    ON real_estate.paiement(id_vente)
    WHERE id_vente IS NOT NULL;


CREATE INDEX idx_paiement_chasseur_beneficiaire
    ON real_estate.paiement(id_chasseur_beneficiaire)
    WHERE id_chasseur_beneficiaire IS NOT NULL;

CREATE INDEX idx_paiement_parametres_honoraires
    ON real_estate.paiement(id_parametres_honoraires)
    WHERE id_parametres_honoraires IS NOT NULL;

CREATE INDEX idx_paiement_parametres_remuneration
    ON real_estate.paiement(id_parametres_remuneration)
    WHERE id_parametres_remuneration IS NOT NULL;

CREATE INDEX idx_paiement_date_calcul
    ON real_estate.paiement(date_calcul)
    WHERE date_calcul IS NOT NULL;

CREATE INDEX idx_paiement_droit_remuneration
    ON real_estate.paiement(droit_remuneration)
    WHERE droit_remuneration IS NOT NULL;


-- =============================================================================
-- 7. Documentation comments
-- =============================================================================

COMMENT ON TABLE real_estate.vente IS
    'Completed property transaction identified by authentic deed; source event for remuneration calculation.';

COMMENT ON COLUMN real_estate.vente.id_mandat_periode IS
    'Contractual Mandat period valid for the deed when applicable; may be NULL when no valid period exists.';

COMMENT ON COLUMN real_estate.vente.id_chasseur_beneficiaire IS
    'Single internal hunter beneficiary when remuneration entitlement exists; NULL when no internal beneficiary exists.';

COMMENT ON COLUMN real_estate.vente.origine_vente IS
    'Origin of successful transaction: CHASSEUR, CLIENT_SEUL, or AUTRE_AGENCE.';

COMMENT ON TABLE real_estate.parametres_honoraires IS
    'Versioned company-fee parameters used for H = fixed amount + percentage * purchase price.';

COMMENT ON TABLE real_estate.parametres_remuneration IS
    'Versioned parameters controlling the five-factor performance score and remuneration modulation.';

COMMENT ON TABLE real_estate.palier_performance IS
    'Configurable performance scoring bands for Mandat-to-deed delay and visits-before-purchase criteria.';

COMMENT ON COLUMN real_estate.paiement.droit_remuneration IS
    'Frozen entitlement decision produced before monetary remuneration calculation.';

COMMENT ON COLUMN real_estate.paiement.motif_refus IS
    'Frozen reason when remuneration entitlement is denied.';

COMMENT ON COLUMN real_estate.paiement.score_performance IS
    'Frozen five-factor performance score at remuneration calculation time.';

COMMENT ON COLUMN real_estate.paiement.taux_final IS
    'Frozen final hunter remuneration rate applied to company fees, never directly to purchase price.';


-- =============================================================================
-- 8. Migration registry
-- =============================================================================

INSERT INTO migration_control.schema_version (
    version,
    description
)
VALUES (
    '010',
    'Add transaction and auditable remuneration calculation foundation'
);

COMMIT;