-- Agency fees collected on behalf of the company, not notary remuneration.
\set ON_ERROR_STOP on
BEGIN;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM migration_control.schema_version WHERE version = '018') THEN
        RAISE EXCEPTION 'Migration 019 requires migration 018' USING ERRCODE = '23514';
    END IF;
    IF EXISTS (SELECT 1 FROM migration_control.schema_version WHERE version = '019') THEN
        RAISE EXCEPTION 'Migration 019 already applied' USING ERRCODE = '23514';
    END IF;
END $$;

CREATE TABLE real_estate.notaire (
    id_notaire BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(200) NOT NULL CHECK (length(trim(nom)) > 0),
    office VARCHAR(200) NOT NULL CHECK (length(trim(office)) > 0),
    email VARCHAR(254) NOT NULL CHECK (length(trim(email)) > 0)
);
CREATE TABLE real_estate.dossier_notarial (
    id_dossier_notarial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_notaire BIGINT NOT NULL REFERENCES real_estate.notaire ON DELETE RESTRICT,
    id_offre BIGINT NOT NULL REFERENCES real_estate.offre ON DELETE RESTRICT,
    id_vente BIGINT REFERENCES real_estate.vente ON DELETE RESTRICT,
    date_rendez_vous TIMESTAMPTZ NOT NULL,
    reference_acte VARCHAR(120) CHECK (length(trim(reference_acte)) > 0),
    reference_document VARCHAR(500) CHECK (length(trim(reference_document)) > 0),
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dossier_notarial_offre UNIQUE (id_offre),
    CONSTRAINT uq_dossier_notarial_vente UNIQUE (id_vente),
    CONSTRAINT uq_dossier_notarial_acte UNIQUE (id_notaire, reference_acte),
    CONSTRAINT ck_dossier_notarial_signature CHECK (
        (id_vente IS NULL AND reference_acte IS NULL AND reference_document IS NULL) OR
        (id_vente IS NOT NULL AND reference_acte IS NOT NULL AND reference_document IS NOT NULL)
    )
);
CREATE TABLE real_estate.mouvement_notarial (
    id_mouvement_notarial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier_notarial BIGINT NOT NULL REFERENCES real_estate.dossier_notarial ON DELETE RESTRICT,
    nature VARCHAR(30) NOT NULL,
    montant NUMERIC(14,2) NOT NULL,
    date_operation DATE NOT NULL,
    reference VARCHAR(120) NOT NULL CHECK (length(trim(reference)) > 0),
    date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mouvement_notarial_reference UNIQUE (id_dossier_notarial, reference),
    CONSTRAINT ck_mouvement_notarial_nature CHECK (nature IN ('COLLECTE_NOTAIRE', 'RECEPTION_ENTREPRISE')),
    CONSTRAINT ck_mouvement_notarial_montant CHECK (montant > 0)
);

CREATE FUNCTION real_estate.guard_dossier_notarial() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE offer real_estate.offre; sale real_estate.vente; mandate BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Notarial dossiers cannot be deleted' USING ERRCODE = '23514'; END IF;
    IF TG_OP = 'UPDATE' AND (OLD.id_vente IS NOT NULL OR NEW.id_offre <> OLD.id_offre OR NEW.id_notaire <> OLD.id_notaire) THEN
        RAISE EXCEPTION 'Signed dossiers and dossier parties are immutable' USING ERRCODE = '23514';
    END IF;
    SELECT * INTO offer FROM real_estate.offre WHERE id_offre = NEW.id_offre FOR UPDATE;
    SELECT d.id_mandat INTO mandate FROM real_estate.presentation p
      JOIN real_estate.demande_version dv USING (id_demande_version)
      JOIN real_estate.demande d USING (id_demande)
      WHERE p.id_presentation = offer.id_presentation;
    IF offer.statut IS DISTINCT FROM 'ACCEPTEE' OR mandate IS NULL THEN
        RAISE EXCEPTION 'Dossier requires an accepted offer linked to a mandate' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'INSERT' AND EXISTS (SELECT 1 FROM real_estate.vente WHERE id_presentation = offer.id_presentation) THEN
        RAISE EXCEPTION 'Create the notarial dossier before completing the sale' USING ERRCODE = '23514';
    END IF;
    IF NEW.id_vente IS NOT NULL THEN
        SELECT * INTO sale FROM real_estate.vente WHERE id_vente = NEW.id_vente;
        IF sale.id_presentation IS DISTINCT FROM offer.id_presentation OR sale.id_mandat IS DISTINCT FROM mandate
           OR sale.date_acte_authentique < (NEW.date_rendez_vous AT TIME ZONE 'UTC')::date
           OR sale.date_acte_authentique < (offer.date_decision AT TIME ZONE 'UTC')::date
           OR sale.date_acte_authentique > CURRENT_DATE THEN
            RAISE EXCEPTION 'Authentic deed conflicts with offer, appointment or mandate' USING ERRCODE = '23514';
        END IF;
        IF EXISTS (SELECT 1 FROM real_estate.paiement WHERE id_vente = NEW.id_vente AND statut <> 'ATTENDU') THEN
            RAISE EXCEPTION 'Cannot attach a dossier to an already processed payment' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER guard_dossier_notarial BEFORE INSERT OR UPDATE OR DELETE ON real_estate.dossier_notarial
FOR EACH ROW EXECUTE FUNCTION real_estate.guard_dossier_notarial();

CREATE FUNCTION real_estate.guard_mouvement_notarial() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE sale_id BIGINT; payment real_estate.paiement; collected NUMERIC; received NUMERIC; last_date DATE;
BEGIN
    IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Notarial financial movements are append-only' USING ERRCODE = '23514'; END IF;
    SELECT id_vente INTO sale_id FROM real_estate.dossier_notarial WHERE id_dossier_notarial = NEW.id_dossier_notarial;
    SELECT * INTO payment FROM real_estate.paiement WHERE id_vente = sale_id FOR UPDATE;
    PERFORM 1 FROM real_estate.dossier_notarial WHERE id_dossier_notarial = NEW.id_dossier_notarial FOR UPDATE;
    IF payment.id_paiement IS NULL OR payment.statut <> 'ATTENDU' OR payment.montant_honoraires IS NULL THEN
        RAISE EXCEPTION 'Expected agency fee payment required' USING ERRCODE = '23514';
    END IF;
    SELECT coalesce(sum(montant) FILTER (WHERE nature = 'COLLECTE_NOTAIRE'), 0),
           coalesce(sum(montant) FILTER (WHERE nature = 'RECEPTION_ENTREPRISE'), 0), max(date_operation)
      INTO collected, received, last_date FROM real_estate.mouvement_notarial
      WHERE id_dossier_notarial = NEW.id_dossier_notarial;
    IF NEW.date_operation < payment.date_acte_authentique OR NEW.date_operation > CURRENT_DATE
       OR NEW.date_operation < last_date THEN RAISE EXCEPTION 'Invalid movement chronology' USING ERRCODE = '23514'; END IF;
    IF NEW.nature = 'COLLECTE_NOTAIRE' THEN collected := collected + NEW.montant;
    ELSE received := received + NEW.montant; END IF;
    IF received > collected OR collected > payment.montant_honoraires THEN
        RAISE EXCEPTION 'Agency fee reconciliation exceeded' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER guard_mouvement_notarial BEFORE INSERT OR UPDATE OR DELETE ON real_estate.mouvement_notarial
FOR EACH ROW EXECUTE FUNCTION real_estate.guard_mouvement_notarial();

CREATE FUNCTION real_estate.guard_notarial_payment() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE dossier_id BIGINT; total NUMERIC; last_date DATE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF EXISTS (SELECT 1 FROM real_estate.dossier_notarial d JOIN real_estate.mouvement_notarial m USING (id_dossier_notarial)
                   WHERE d.id_vente = OLD.id_vente) THEN
            RAISE EXCEPTION 'Payment with notarial movements cannot be deleted' USING ERRCODE = '23514';
        END IF;
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND EXISTS (
        SELECT 1 FROM real_estate.dossier_notarial d JOIN real_estate.mouvement_notarial m USING (id_dossier_notarial)
        WHERE d.id_vente = OLD.id_vente
    ) AND (NEW.id_vente IS DISTINCT FROM OLD.id_vente OR NEW.montant_honoraires IS DISTINCT FROM OLD.montant_honoraires
           OR NEW.montant_achat IS DISTINCT FROM OLD.montant_achat OR NEW.date_acte_authentique IS DISTINCT FROM OLD.date_acte_authentique
           OR NEW.id_mandat IS DISTINCT FROM OLD.id_mandat OR NEW.id_parametres_honoraires IS DISTINCT FROM OLD.id_parametres_honoraires) THEN
        RAISE EXCEPTION 'Notarial financial basis is frozen after collection' USING ERRCODE = '23514';
    END IF;
    SELECT id_dossier_notarial INTO dossier_id FROM real_estate.dossier_notarial WHERE id_vente = NEW.id_vente;
    IF dossier_id IS NOT NULL AND NEW.statut IN ('RECU', 'VERIFIE', 'PROGRAMME', 'PAYE') THEN
        SELECT coalesce(sum(montant), 0), max(date_operation) INTO total, last_date
          FROM real_estate.mouvement_notarial WHERE id_dossier_notarial = dossier_id AND nature = 'RECEPTION_ENTREPRISE';
        IF total IS DISTINCT FROM NEW.montant_honoraires OR last_date IS DISTINCT FROM NEW.date_reception_honoraires THEN
            RAISE EXCEPTION 'Full notarial company receipt required' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER guard_notarial_payment BEFORE INSERT OR UPDATE OR DELETE ON real_estate.paiement
FOR EACH ROW EXECUTE FUNCTION real_estate.guard_notarial_payment();

CREATE FUNCTION real_estate.guard_notarial_sale() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM real_estate.dossier_notarial WHERE id_vente = OLD.id_vente) THEN
        RAISE EXCEPTION 'Authenticated notarial sale is immutable' USING ERRCODE = '23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM real_estate.dossier_notarial d JOIN real_estate.offre o USING (id_offre)
        WHERE o.id_presentation = NEW.id_presentation AND d.id_vente IS DISTINCT FROM NEW.id_vente
    ) THEN RAISE EXCEPTION 'Complete this sale through its notarial dossier' USING ERRCODE = '23514'; END IF;
    RETURN NEW;
END $$;
-- Signature creates the sale and links the dossier in one transaction.
CREATE CONSTRAINT TRIGGER guard_notarial_sale AFTER INSERT OR UPDATE ON real_estate.vente
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION real_estate.guard_notarial_sale();

CREATE TABLE warehouse.fact_dossier_notarial (
    id_dossier_source BIGINT PRIMARY KEY,
    id_notaire_source BIGINT NOT NULL,
    id_vente_source BIGINT,
    acte_signe BOOLEAN NOT NULL,
    honoraires_attendus NUMERIC(14,2),
    montant_collecte NUMERIC(14,2) NOT NULL,
    montant_recu NUMERIC(14,2) NOT NULL,
    derniere_reception DATE,
    dw_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE real_estate.mouvement_notarial IS 'Agency fee accounting basis follows paiement.montant_honoraires; excludes purchase price, notary own fees and tax calculations.';
INSERT INTO migration_control.schema_version(version, description) VALUES ('019', 'Notarial deeds and agency fee collection versus company receipt');
COMMIT;
