apiVersion: v1
kind: Service

metadata:
  name: real-estate-backend
  namespace: real-estate

  labels:
    app: real-estate-backend

spec:
  type: ClusterIP

  selector:
    app: real-estate-backend

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP